//! Gemini-shaped `generateContent` over SSE.
//!
//! A third module rather than a branch in `openai.rs`, because the differences
//! are larger than the ones between the other two shapes: roles are
//! `user`/`model`, history is `contents[].parts[]`, tool calls carry no id at
//! all, the system prompt is a `systemInstruction` object, and each SSE frame is
//! a complete response rather than a delta envelope.
//!
//! The request builder and the frame folder are pure functions so they can be
//! tested without a network; only `stream_response` touches HTTP.

use super::protocol::{StreamEvent, ToolDefinition, Turn, Usage};
use crate::error::{AppError, AppResult};
use serde_json::json;
use std::collections::BTreeMap;

pub fn build_request(
    system_prompt: Option<&str>,
    tools: &[ToolDefinition],
    history: &[Turn],
) -> serde_json::Value {
    let mut contents: Vec<serde_json::Value> = Vec::new();
    for turn in history {
        append_turn(&mut contents, turn);
    }

    let mut body = json!({ "contents": contents });
    // Not a message in the list — a sibling of it.
    if let Some(system_prompt) = system_prompt.filter(|text| !text.trim().is_empty()) {
        body["systemInstruction"] = json!({ "parts": [{ "text": system_prompt }] });
    }
    if !tools.is_empty() {
        body["tools"] = json!([{
            "functionDeclarations": tools
                .iter()
                .map(|tool| json!({
                    "name": tool.name,
                    "description": tool.description,
                    "parameters": sanitize_schema(&tool.input_schema),
                }))
                .collect::<Vec<_>>(),
        }]);
    }
    body
}

/// Strips the JSON Schema keywords Gemini rejects outright.
///
/// The MCP tools' schemas are generated by `schemars` and carry `$schema` and
/// `additionalProperties`, which this API answers with a 400 rather than
/// ignoring. Recursive because nested object properties carry them too.
fn sanitize_schema(schema: &serde_json::Value) -> serde_json::Value {
    const REJECTED: [&str; 4] = ["$schema", "$id", "additionalProperties", "definitions"];

    match schema {
        serde_json::Value::Object(fields) => {
            let mut kept = serde_json::Map::new();
            for (key, value) in fields {
                if REJECTED.contains(&key.as_str()) {
                    continue;
                }
                kept.insert(key.clone(), sanitize_schema(value));
            }
            serde_json::Value::Object(kept)
        }
        serde_json::Value::Array(items) => {
            serde_json::Value::Array(items.iter().map(sanitize_schema).collect())
        }
        other => other.clone(),
    }
}

fn append_turn(contents: &mut Vec<serde_json::Value>, turn: &Turn) {
    match turn {
        Turn::User { text } => {
            contents.push(json!({ "role": "user", "parts": [{ "text": text }] }));
        }
        Turn::Assistant { text, tool_calls } => {
            let mut parts: Vec<serde_json::Value> = Vec::new();
            if let Some(text) = text.as_deref().filter(|text| !text.is_empty()) {
                parts.push(json!({ "text": text }));
            }
            for call in tool_calls {
                // No id field exists here: a call is identified by its name.
                parts.push(json!({
                    "functionCall": { "name": call.tool, "args": call.args },
                }));
            }
            // The assistant role is called "model".
            if !parts.is_empty() {
                contents.push(json!({ "role": "model", "parts": parts }));
            }
        }
        Turn::ToolResult {
            tool,
            content,
            is_error,
            ..
        } => {
            // A result is a user-role part naming the function it answers. The
            // response must be an object, so free text is wrapped — and a failure
            // is labelled rather than hidden, so the model can retry differently.
            let response = if *is_error {
                json!({ "error": content })
            } else {
                json!({ "result": content })
            };
            contents.push(json!({
                "role": "user",
                "parts": [{ "functionResponse": { "name": tool, "response": response } }],
            }));
        }
    }
}

/// Folds SSE frames into provider-neutral stream events.
///
/// Unlike the other two shapes there is nothing to accumulate: every frame is a
/// whole `GenerateContentResponse`, so a `functionCall` part arrives with its
/// arguments already complete.
#[derive(Debug, Default)]
pub struct StreamFolder {
    usage: Usage,
    finished: bool,
}

impl StreamFolder {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn usage(&self) -> Usage {
        self.usage
    }

    pub fn is_finished(&self) -> bool {
        self.finished
    }

    /// Handles one frame's payload.
    pub fn push_payload(&mut self, payload: &str) -> Vec<StreamEvent> {
        let Ok(data) = serde_json::from_str::<serde_json::Value>(payload) else {
            return Vec::new();
        };

        // An in-stream error arrives as a body rather than an HTTP status, so it
        // must not be silently swallowed.
        if let Some(message) = data
            .get("error")
            .and_then(|error| error.get("message"))
            .and_then(|message| message.as_str())
        {
            return self.finish(Some(format!("error: {message}")));
        }

        self.capture_usage(data.get("usageMetadata"));

        let mut events = Vec::new();
        let candidate = data
            .get("candidates")
            .and_then(|candidates| candidates.as_array())
            .and_then(|candidates| candidates.first());

        if let Some(parts) = candidate
            .and_then(|candidate| candidate.get("content"))
            .and_then(|content| content.get("parts"))
            .and_then(|parts| parts.as_array())
        {
            for part in parts {
                if let Some(text) = part
                    .get("text")
                    .and_then(|text| text.as_str())
                    .filter(|text| !text.is_empty())
                {
                    events.push(StreamEvent::TextDelta(text.to_string()));
                }
                if let Some(call) = part.get("functionCall") {
                    if let Some(name) = call.get("name").and_then(|name| name.as_str()) {
                        events.push(StreamEvent::ToolCall {
                            // The wire format has no id, but the rest of the app
                            // correlates results by one, so it is minted here.
                            call_id: uuid::Uuid::new_v4().to_string(),
                            tool: name.to_string(),
                            arguments: call
                                .get("args")
                                .map(|args| args.to_string())
                                .unwrap_or_else(|| "{}".to_string()),
                        });
                    }
                }
            }
        }

        if let Some(reason) = candidate
            .and_then(|candidate| candidate.get("finishReason"))
            .and_then(|reason| reason.as_str())
            .filter(|reason| !reason.is_empty())
        {
            events.extend(self.finish(Some(reason.to_string())));
        }

        events
    }

    fn capture_usage(&mut self, usage: Option<&serde_json::Value>) {
        let Some(usage) = usage else { return };
        if let Some(input) = usage.get("promptTokenCount").and_then(|v| v.as_i64()) {
            self.usage.input_tokens = Some(input);
        }
        if let Some(output) = usage.get("candidatesTokenCount").and_then(|v| v.as_i64()) {
            self.usage.output_tokens = Some(output);
        }
    }

    /// Ends the response. Idempotent: a stream carrying `finishReason` on more
    /// than one frame must not yield two `Done`s.
    pub fn finish(&mut self, stop_reason: Option<String>) -> Vec<StreamEvent> {
        if self.finished {
            return Vec::new();
        }
        self.finished = true;
        vec![StreamEvent::Done { stop_reason }]
    }
}

/// Turns a non-2xx response into something the user can act on.
///
/// The error envelope is `{"error": {"message": ...}}`, same as the other two,
/// so the shared wording applies — but the 404 hint differs: this API's paths
/// are versioned as `/v1beta` rather than `/v1`.
pub fn describe_failure(status: u16, body: &str) -> String {
    let detail = serde_json::from_str::<serde_json::Value>(body)
        .ok()
        .and_then(|value| {
            value
                .get("error")
                .and_then(|error| error.get("message"))
                .or_else(|| value.get("message"))
                .and_then(|message| message.as_str())
                .map(|message| message.chars().take(300).collect::<String>())
        })
        .map(|message| format!(" {message}"))
        .unwrap_or_default();
    match status {
        400 => format!("The provider rejected the request ({status}).{detail}"),
        401 | 403 => format!("Authentication failed ({status}). Check the API key.{detail}"),
        404 => format!(
            "No such model or path at this address ({status}). Check the model id and whether the base URL should end in /v1beta.{detail}"
        ),
        429 => format!("Rate limited by the provider ({status}).{detail}"),
        _ => format!("The provider returned HTTP {status}.{detail}"),
    }
}

/// The streaming URL. The model id is part of the path here, not the body, and
/// `alt=sse` is what turns the response into an event stream rather than a JSON
/// array.
pub fn stream_url(base_url: &str, model: &str) -> String {
    format!(
        "{}/models/{}:streamGenerateContent?alt=sse",
        base_url.trim_end_matches('/'),
        model
    )
}

/// Issues the streaming request. `on_event` sees each event as it is produced.
pub async fn stream_response(
    base_url: &str,
    model: &str,
    api_key: &str,
    headers: &BTreeMap<String, String>,
    body: &serde_json::Value,
    cancel: &tokio_util::sync::CancellationToken,
    mut on_event: impl FnMut(StreamEvent),
) -> AppResult<Usage> {
    use futures_util::StreamExt;

    let url = stream_url(base_url, model);
    let client = reqwest::Client::builder()
        .build()
        .map_err(|error| AppError::internal(error.to_string()))?;

    let mut request = client.post(&url).header("x-goog-api-key", api_key);
    for (name, value) in headers {
        request = request.header(name, value);
    }

    let response = request.json(body).send().await.map_err(|error| {
        AppError::internal(super::openai::describe_transport_failure(&url, &error))
    })?;

    let status = response.status();
    if !status.is_success() {
        let text = response.text().await.unwrap_or_default();
        // Tagged so a caller holding several keys can retire this one and retry.
        return Err(super::protocol::http_failure(
            status.as_u16(),
            describe_failure(status.as_u16(), &text),
        ));
    }

    let mut parser = super::sse::SseParser::new();
    let mut folder = StreamFolder::new();
    let mut bytes = response.bytes_stream();

    loop {
        let chunk = tokio::select! {
            // Stopping mid-stream is a user action, not an error.
            _ = cancel.cancelled() => return Ok(folder.usage()),
            chunk = bytes.next() => chunk,
        };
        let Some(chunk) = chunk else { break };
        let chunk = chunk.map_err(|error| AppError::internal(error.to_string()))?;

        for event in parser.push(&String::from_utf8_lossy(&chunk)) {
            for produced in folder.push_payload(&event.data) {
                on_event(produced);
            }
        }
        if folder.is_finished() {
            return Ok(folder.usage());
        }
    }

    if let Some(event) = parser.finish() {
        for produced in folder.push_payload(&event.data) {
            on_event(produced);
        }
    }
    for produced in folder.finish(None) {
        on_event(produced);
    }
    Ok(folder.usage())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::models::ChatToolCall;

    fn tool() -> ToolDefinition {
        ToolDefinition {
            name: "find_job".to_string(),
            description: Some("Locate a job".to_string()),
            input_schema: json!({
                "$schema": "https://json-schema.org/draft/2020-12/schema",
                "type": "object",
                "additionalProperties": false,
                "properties": {"jobId": {"type": "string"}}
            }),
        }
    }

    #[test]
    fn the_system_prompt_is_a_sibling_of_the_contents() {
        let body = build_request(
            Some("be terse"),
            &[],
            &[Turn::User {
                text: "hi".to_string(),
            }],
        );
        assert_eq!(body["systemInstruction"]["parts"][0]["text"], "be terse");
        // It is not smuggled into the message list.
        let contents = body["contents"].as_array().unwrap();
        assert_eq!(contents.len(), 1);
        assert_eq!(contents[0]["role"], "user");
        assert_eq!(contents[0]["parts"][0]["text"], "hi");
    }

    #[test]
    fn a_blank_system_prompt_is_omitted() {
        let body = build_request(Some("   "), &[], &[]);
        assert!(body.get("systemInstruction").is_none());
        assert!(body.get("tools").is_none());
    }

    #[test]
    fn tools_are_declared_with_schemas_this_api_accepts() {
        let body = build_request(None, &[tool()], &[]);
        let declaration = &body["tools"][0]["functionDeclarations"][0];
        assert_eq!(declaration["name"], "find_job");
        // The parameters key is not called "input_schema" here.
        assert_eq!(declaration["parameters"]["type"], "object");
        assert_eq!(
            declaration["parameters"]["properties"]["jobId"]["type"],
            "string"
        );
        // Keywords this API answers with a 400 are stripped rather than sent.
        assert!(declaration["parameters"].get("$schema").is_none());
        assert!(declaration["parameters"].get("additionalProperties").is_none());
    }

    #[test]
    fn nested_schemas_are_sanitized_too() {
        let sanitized = sanitize_schema(&json!({
            "type": "object",
            "properties": {
                "nested": {"type": "object", "additionalProperties": false, "$schema": "x"}
            }
        }));
        assert!(sanitized["properties"]["nested"]
            .get("additionalProperties")
            .is_none());
        assert!(sanitized["properties"]["nested"].get("$schema").is_none());
        assert_eq!(sanitized["properties"]["nested"]["type"], "object");
    }

    #[test]
    fn the_assistant_role_is_called_model_and_calls_carry_no_id() {
        let body = build_request(
            None,
            &[],
            &[Turn::Assistant {
                text: Some("checking".to_string()),
                tool_calls: vec![ChatToolCall {
                    call_id: "c-1".to_string(),
                    tool: "find_job".to_string(),
                    args: json!({"jobId": "abc"}),
                    result: None,
                    error: None,
                    duration_ms: None,
                }],
            }],
        );
        let content = &body["contents"][0];
        assert_eq!(content["role"], "model");
        assert_eq!(content["parts"][0]["text"], "checking");
        let call = &content["parts"][1]["functionCall"];
        assert_eq!(call["name"], "find_job");
        // Args are an object here, not a JSON string.
        assert_eq!(call["args"]["jobId"], "abc");
        assert!(call.get("id").is_none());
    }

    #[test]
    fn an_empty_assistant_turn_is_skipped() {
        // An aborted send leaves a row with neither text nor calls; replaying it
        // would break the role alternation.
        let body = build_request(
            None,
            &[],
            &[Turn::Assistant {
                text: None,
                tool_calls: vec![],
            }],
        );
        assert!(body["contents"].as_array().unwrap().is_empty());
    }

    #[test]
    fn tool_results_reference_the_function_by_name_and_flag_failures() {
        let body = build_request(
            None,
            &[],
            &[
                Turn::ToolResult {
                    call_id: "c-1".to_string(),
                    tool: "find_job".to_string(),
                    content: "{\"id\":\"abc\"}".to_string(),
                    is_error: false,
                },
                Turn::ToolResult {
                    call_id: "c-2".to_string(),
                    tool: "get_job_log_text".to_string(),
                    content: "no such log".to_string(),
                    is_error: true,
                },
            ],
        );
        let ok = &body["contents"][0]["parts"][0]["functionResponse"];
        assert_eq!(body["contents"][0]["role"], "user");
        assert_eq!(ok["name"], "find_job");
        assert_eq!(ok["response"]["result"], "{\"id\":\"abc\"}");

        // The model is told the call failed rather than being handed a blank.
        let failed = &body["contents"][1]["parts"][0]["functionResponse"];
        assert_eq!(failed["response"]["error"], "no such log");
    }

    #[test]
    fn text_frames_become_deltas() {
        let mut folder = StreamFolder::new();
        let events = folder.push_payload(
            r#"{"candidates":[{"content":{"role":"model","parts":[{"text":"the driver "}]}}]}"#,
        );
        assert_eq!(events, vec![StreamEvent::TextDelta("the driver ".to_string())]);
        assert!(!folder.is_finished());
    }

    #[test]
    fn a_function_call_arrives_complete_in_one_frame() {
        let mut folder = StreamFolder::new();
        let events = folder.push_payload(
            r#"{"candidates":[{"content":{"parts":[
                {"functionCall":{"name":"find_job","args":{"jobId":"abc"}}}
            ]}}]}"#,
        );
        assert_eq!(events.len(), 1);
        match &events[0] {
            StreamEvent::ToolCall {
                call_id,
                tool,
                arguments,
            } => {
                assert_eq!(tool, "find_job");
                assert_eq!(arguments, r#"{"jobId":"abc"}"#);
                // The wire format has no id, so one is minted to correlate the
                // result.
                assert!(!call_id.is_empty());
            }
            other => panic!("expected a tool call, got {other:?}"),
        }
    }

    #[test]
    fn an_argument_less_call_defaults_to_an_empty_object() {
        let mut folder = StreamFolder::new();
        let events = folder
            .push_payload(r#"{"candidates":[{"content":{"parts":[{"functionCall":{"name":"list_accounts"}}]}}]}"#);
        assert_eq!(
            events,
            vec![StreamEvent::ToolCall {
                call_id: match &events[0] {
                    StreamEvent::ToolCall { call_id, .. } => call_id.clone(),
                    _ => unreachable!(),
                },
                tool: "list_accounts".to_string(),
                arguments: "{}".to_string(),
            }]
        );
    }

    #[test]
    fn a_finish_reason_ends_the_stream_once() {
        let mut folder = StreamFolder::new();
        let events = folder.push_payload(
            r#"{"candidates":[{"content":{"parts":[{"text":"done"}]},"finishReason":"STOP"}],
                "usageMetadata":{"promptTokenCount":12,"candidatesTokenCount":3}}"#,
        );
        assert_eq!(
            events,
            vec![
                StreamEvent::TextDelta("done".to_string()),
                StreamEvent::Done {
                    stop_reason: Some("STOP".to_string())
                }
            ]
        );
        assert_eq!(folder.usage().input_tokens, Some(12));
        assert_eq!(folder.usage().output_tokens, Some(3));

        // A second terminator must not produce a second Done.
        assert!(folder
            .push_payload(r#"{"candidates":[{"finishReason":"STOP"}]}"#)
            .is_empty());
        assert!(folder.finish(None).is_empty());
    }

    #[test]
    fn an_in_stream_error_ends_the_response_rather_than_being_ignored() {
        let mut folder = StreamFolder::new();
        let events =
            folder.push_payload(r#"{"error":{"code":429,"message":"quota exhausted"}}"#);
        assert_eq!(
            events,
            vec![StreamEvent::Done {
                stop_reason: Some("error: quota exhausted".to_string())
            }]
        );
        assert!(folder.is_finished());
    }

    #[test]
    fn keep_alives_and_junk_frames_are_ignored() {
        let mut folder = StreamFolder::new();
        assert!(folder.push_payload("").is_empty());
        assert!(folder.push_payload("not json").is_empty());
        assert!(folder.push_payload("{}").is_empty());
        assert!(!folder.is_finished());
    }

    #[test]
    fn the_model_id_goes_in_the_path_with_sse_requested() {
        assert_eq!(
            stream_url("https://generativelanguage.googleapis.com/v1beta", "gemini-3.5-flash"),
            "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:streamGenerateContent?alt=sse"
        );
        // A trailing slash on the configured address must not double up.
        assert_eq!(
            stream_url("https://x.example/v1beta/", "m"),
            "https://x.example/v1beta/models/m:streamGenerateContent?alt=sse"
        );
    }

    #[test]
    fn http_failures_explain_the_likely_cause() {
        let unauthorized = describe_failure(401, r#"{"error":{"message":"bad key"}}"#);
        assert!(unauthorized.contains("API key"), "{unauthorized}");
        assert!(unauthorized.contains("bad key"), "{unauthorized}");

        // The version hint is /v1beta here, not /v1.
        let missing = describe_failure(404, "");
        assert!(missing.contains("/v1beta"), "{missing}");

        let rejected = describe_failure(400, r#"{"error":{"message":"unknown field"}}"#);
        assert!(rejected.contains("unknown field"), "{rejected}");
    }
}
